### ISSUE TITLE
Starlight + Dimensional Threads crash

### ISSUE THREAD

**Issue by TelepathicGrunt** [Spottedleaf/Starlight#48]
A modpack put in my mod World Blender, Dimensional Threads, and StarLight. However, in my dimension, the game crashes. I reported the issue to Dimensional Threads but they closed the report: https://github.com/WearBlackAllDay/DimensionalThreading/issues/21 

The crash appears during World Blender's entity ticking but does not appear in the stacktrace. Instead Starlight does. Here's the crash stacktrace from the latest.log that was given to me by the modpack dev
https://paste.ee/p/7PQ0o

Here's my ticking code for my entity
https://github.com/TelepathicGrunt/WorldBlender-Fabric/blob/35e2237f7657487b8c38ae649f79d5e7a513397e/src/main/java/com/telepathicgrunt/worldblender/entities/ItemClearingEntity.java#L60-L126

I'm wondering if it because I am removing a ton of blocks when my entity tick at first. And that change of blocks causes StarLight to try and recalculate lighting for the area and then crashes due to DimensionalThreading trying to multithread the dimension.

Sorry I couldn't be of more help. Hopefully this is enough to try and get a reproducible case with all three mods on.

**Comment by WearBlackAllDay** [comment]
Hello @TelepathicGrunt 
Just opened a new Issue on my repo for discussion about possible errorsources concerning your crashreport that are linked do DimThread code.
I am not yet done with ruling out or confirming DimThreads involvement in the crash, I closed the original Issuee, because the initial opening reason has nothing to do with your crash and is resolved.

**Comment by Spottedleaf** [comment]
The `java.util.ConcurrentModificationException` should be fixed as of 1.0.0-RC2. If not, please re-open.

**Comment by TelepathicGrunt** [comment]
I gotten the modpack dev to switch to 1.0.0-RC2 Starlight and try again. However, the crash still occurred with this as the log: https://paste.alloffabric.com/emikoseyuj.yaml

They said they do not know why the past says RC1 when they only have RC2 on. I'll poke them more about that
(also, i dont have to ability to reopen issue report)

EDIT: seems like they might had screwed up getting RC2 and was running RC1 still. Hang on

**Comment by Spottedleaf** [comment]
Log indicates RC1 is being used.
